version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-networks

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
