# Generated by Django 5.1 on 2024-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_comment_visit_delete_pagevisit_comment_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
