# Generated by Django 5.0.7 on 2024-07-19 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet', models.CharField(max_length=140)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('retweet', models.IntegerField(default=0)),
                ('reply', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('save', models.IntegerField(default=0)),
                ('hashtag', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('sentiment', models.CharField(max_length=50)),
                ('sentiment_score', models.FloatField(default=0)),
                ('sentiment_polarity', models.FloatField(default=0)),
                ('sentiment_subjectivity', models.FloatField(default=0)),
                ('sentiment_confidence', models.FloatField(default=0)),
                ('sentiment_magnitude', models.FloatField(default=0)),
                ('sentiment_neg', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
