# Generated by Django 5.0.6 on 2024-07-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChaiVarity',
            new_name='ChaiVariety',
        ),
    ]
