# Generated by Django 5.0.6 on 2024-07-01 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('nextjs', 'Next-js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('django', 'Django'), ('flask', 'Flask'), ('laravel', 'Laravel'), ('spring', 'Spring'), ('nodejs', 'Node.js'), ('express', 'Express'), ('ruby', 'Ruby'), ('rails', 'Rails')], max_length=7)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
